root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp\\server.exe"
  cmd = "go build -o tmp/server.exe cmd/server/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  kill_delay = "0s"
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true